"use client"

import Header from "@/components/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { createWeb3Modal } from "@web3modal/wagmi/react"
import { walletConnectProvider, EIP6963Connector } from "@web3modal/wagmi"

import { WagmiConfig, configureChains, createConfig } from "wagmi"
import { publicProvider } from "wagmi/providers/public"
import { mainnet } from "wagmi/chains"
import { InjectedConnector } from "wagmi/connectors/injected"
import { WalletConnectConnector } from "wagmi/connectors/walletConnect"
import { ThemeProvider } from "styled-components"
import { ThorinGlobalStyles, lightTheme } from "@ensdomains/thorin"

// 1. Get projectId
const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID as string

// 2. Create wagmiConfig
const { chains, publicClient } = configureChains(
  [mainnet],
  [walletConnectProvider({ projectId }), publicProvider()]
)

const appData = {
  name: "Docissue",
  description: "Web3 Document Issuer/Viewer",
}

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [
    new WalletConnectConnector({
      chains,
      options: { projectId, showQrModal: false, metadata: appData },
    }),
    new EIP6963Connector({ chains }),
    new InjectedConnector({ chains, options: { shimDisconnect: true } }),
  ],
  publicClient,
})

// 3. Create modal
createWeb3Modal({ wagmiConfig, projectId, chains, themeMode: "light" })

const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={wagmiConfig}>
          <ThemeProvider theme={lightTheme}>
            <ThorinGlobalStyles />
            <div className="min-h-screen px-24">
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </WagmiConfig>
      </body>
    </html>
  )
}
